2024-04-26 19:30:44,060 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'TypeError'>, TypeError('context must be a dict rather than tuple.'), <traceback object at 0x0000024D0E388200>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 57, in render
    context = make_context(
              ^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\context.py", line 286, in make_context
    raise TypeError(
TypeError: context must be a dict rather than tuple.
2024-04-26 19:30:44,063 ERROR "GET /news/ HTTP/1.1" 500 87845 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-26 20:15:54,787 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("<ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template."), <traceback object at 0x00000268F19A7540>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 528, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template.
2024-04-26 20:15:54,804 ERROR "GET /news/ HTTP/1.1" 500 145611 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-26 20:17:00,744 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("<ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template."), <traceback object at 0x00000268F1B7E400>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 528, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template.
2024-04-26 20:17:00,749 ERROR "GET /news/ HTTP/1.1" 500 145748 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-26 20:17:05,870 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("<ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template."), <traceback object at 0x00000268F1AD4D40>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 528, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template.
2024-04-26 20:17:05,878 ERROR "GET /news/ HTTP/1.1" 500 145748 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-26 20:22:23,333 ERROR Internal Server Error: /news/categories/4 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("<ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template."), <traceback object at 0x00000268F1BC8100>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 528, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template.
2024-04-26 20:22:23,346 ERROR "GET /news/categories/4 HTTP/1.1" 500 147763 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-26 20:22:34,692 ERROR Internal Server Error: /news/categories/2 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("<ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template."), <traceback object at 0x00000268F1B7EE80>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 511, in parse
    self.extend_nodelist(nodelist, compiled_result, token)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 528, in extend_nodelist
    raise self.error(
django.template.exceptions.TemplateSyntaxError: <ExtendsNode: extends 'flatpages/default.html'> must be the first tag in the template.
2024-04-26 20:22:34,703 ERROR "GET /news/categories/2 HTTP/1.1" 500 147763 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-26 20:44:30,950 ERROR Internal Server Error: /news/categories/2 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 15: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x00000268F1946480>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2024-04-26 20:44:30,968 ERROR "GET /news/categories/2 HTTP/1.1" 500 227605 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-26 20:46:49,100 ERROR Internal Server Error: /news/categories/2 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 15: 'trans', expected 'endblock'. Did you forget to register or load this tag?"), <traceback object at 0x000001F39BBE0400>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'trans'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'trans', expected 'endblock'. Did you forget to register or load this tag?
2024-04-26 20:46:49,111 ERROR "GET /news/categories/2 HTTP/1.1" 500 227468 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-26 20:47:47,239 ERROR Internal Server Error: /news/categories/2 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\utils\log.py (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 60: 'url_replace', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?"), <traceback object at 0x000001F39BAFD100>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'url_replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 60: 'url_replace', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
2024-04-26 20:47:47,246 ERROR "GET /news/categories/2 HTTP/1.1" 500 223640 C:\Users\podch\PycharmProjects\D17\venv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-27 16:00:57,676 ERROR "GET /news/ HTTP/1.1" 500 196541 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-27 16:05:56,154 ERROR Internal Server Error: /admin/news/post/20/change/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x000001B79DBCB5C0>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1948, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1838, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 837, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 310, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 239, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'required'
2024-04-27 16:05:56,163 ERROR "GET /admin/news/post/20/change/ HTTP/1.1" 500 176607 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-27 16:06:08,454 ERROR Internal Server Error: /admin/news/post/5/change/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x000001B79DDA3840>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1948, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1838, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 837, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 310, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 239, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'required'
2024-04-27 16:06:08,464 ERROR "GET /admin/news/post/5/change/ HTTP/1.1" 500 176561 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-27 16:06:36,703 ERROR Internal Server Error: /admin/news/post/add/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x000001B79DE170C0>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1838, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 837, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 310, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 239, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'required'
2024-04-27 16:06:36,709 ERROR "GET /admin/news/post/add/ HTTP/1.1" 500 175848 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-27 16:17:33,496 ERROR Internal Server Error: /admin/news/post/19/change/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x000001B79DE33880>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1948, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1838, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 837, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 310, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 239, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'required'
2024-04-27 16:17:33,509 ERROR "GET /admin/news/post/19/change/ HTTP/1.1" 500 176627 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-27 16:18:24,642 ERROR Internal Server Error: /admin/news/post/add/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x000001B79DBCEB00>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1838, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 837, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 310, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 239, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'required'
2024-04-27 16:18:24,647 ERROR "GET /admin/news/post/add/ HTTP/1.1" 500 175848 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-27 17:26:41,116 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'TypeError'>, TypeError("join() argument must be str, bytes, or os.PathLike object, not 'dict'"), <traceback object at 0x000001D71C803640>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\generic\list.py", line 174, in get
    context = self.get_context_data()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\news\views.py", line 35, in get_context_data
    return HttpResponse(render( 'posts.html', context))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loaders\base.py", line 17, in get_template
    for origin in self.get_template_sources(template_name):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loaders\cached.py", line 70, in get_template_sources
    yield from loader.get_template_sources(template_name)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loaders\filesystem.py", line 35, in get_template_sources
    name = safe_join(template_dir, template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\_os.py", line 17, in safe_join
    final_path = abspath(join(base, *paths))
                         ^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 147, in join
  File "<frozen genericpath>", line 152, in _check_arg_types
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'dict'
2024-04-27 17:26:41,122 ERROR "GET /news/ HTTP/1.1" 500 226573 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-29 17:33:50,823 ERROR Internal Server Error: /admin/news/post/add/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'AttributeError'>, AttributeError("'NoneType' object has no attribute 'required'"), <traceback object at 0x0000020D1F661540>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 1838, in _changeform_view
    fieldsets = self.get_fieldsets(request, obj)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 355, in get_fieldsets
    request, self.get_form(request, obj, fields=None), obj
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 350, in get_form
    return super().get_form(request, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\contrib\admin\options.py", line 837, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 652, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 310, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\forms\models.py", line 239, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 65, in patch_translation_field
    orig_formfield = self.formfield_for_dbfield(orig_field, request, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 48, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\modeltranslation\admin.py", line 53, in patch_translation_field
    if field.required:
       ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'required'
2024-04-29 17:33:50,832 ERROR "GET /admin/news/post/add/ HTTP/1.1" 500 175948 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-30 16:12:40,108 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.title_en_us'), <traceback object at 0x0000014FCAF20CC0>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_post.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\defaultfilters.py", line 621, in length
    return len(value)
           ^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_post.title_en_us
2024-04-30 16:12:40,130 ERROR "GET /news/ HTTP/1.1" 500 223082 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-30 16:15:46,459 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.title_en_us'), <traceback object at 0x00000153CAFBDF40>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_post.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\defaultfilters.py", line 621, in length
    return len(value)
           ^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_post.title_en_us
2024-04-30 16:15:46,469 ERROR "GET /news/ HTTP/1.1" 500 223082 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-30 16:18:26,070 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.title_en_us'), <traceback object at 0x00000153CAD64380>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_post.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\defaultfilters.py", line 621, in length
    return len(value)
           ^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_post.title_en_us
2024-04-30 16:18:26,080 ERROR "GET /news/ HTTP/1.1" 500 223082 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-30 16:18:31,831 ERROR Internal Server Error: /news/categories/2 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_category.name_en_us'), <traceback object at 0x00000153CB06AC40>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_category.name_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D17\news\views.py", line 102, in get_queryset
    self.category = get_object_or_404(Category, id=self.kwargs['pk'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_category.name_en_us
2024-04-30 16:18:31,841 ERROR "GET /news/categories/2 HTTP/1.1" 500 153499 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-30 17:33:30,616 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.title_en_us'), <traceback object at 0x00000172BC206E00>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_post.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\defaultfilters.py", line 621, in length
    return len(value)
           ^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_post.title_en_us
2024-04-30 17:33:30,628 ERROR "GET /news/ HTTP/1.1" 500 223082 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-30 17:42:37,073 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.title_en_us'), <traceback object at 0x0000021AB14138C0>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_post.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\defaultfilters.py", line 621, in length
    return len(value)
           ^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_post.title_en_us
2024-04-30 17:42:37,085 ERROR "GET /news/ HTTP/1.1" 500 223082 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-30 17:43:37,057 ERROR Internal Server Error: /news/ C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\utils\log.py (<class 'django.db.utils.OperationalError'>, OperationalError('no such column: news_post.title_en_us'), <traceback object at 0x000002D944D4A240>)
Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: news_post.title_en_us

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\base.py", line 737, in resolve
    new_obj = func(obj, *arg_vals)
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\template\defaultfilters.py", line 621, in length
    return len(value)
           ^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: news_post.title_en_us
2024-04-30 17:43:37,085 ERROR "GET /news/ HTTP/1.1" 500 223219 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
2024-04-30 18:19:10,417 ERROR "GET /news/ HTTP/1.1" 500 355789 C:\Users\podch\PycharmProjects\D11-Skillfactory-Cache\myvenv\Lib\site-packages\django\core\servers\basehttp.py None
